### ISSUE TITLE
Cannot find module 

### ISSUE THREAD

**Issue by mylastore** [blikblum/generator-mn#4]
getting this error when I try to run yo mn on ubuntu 18
`internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module '../../utils/configbuilder'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-mn/generators/a`

**Comment by blikblum** [comment]
Version 0.5.1 should fix that. Please test and reopen if still having issues

**Comment by mylastore** [comment]
now i get this error after skipping the extra libraries apparently .gitignore file was not generated so I manually added one and installations seems to work but when done is missing configurations for example on the package json is not adding all needed dependencies, I selected handlebars as my template and on the package json it was missing those dependencies plus configurations on the webpack.coonfig.js also was missing the hbs loader etc so I could not get this run properly. 

 


`events.js:174
      throw er; // Unhandled 'error' event
      ^

AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: /usr/local/lib/node_modules/generator-mn/generators/app/templates/.gitignore
    at EditionInterface.exports.copy (/usr/local/lib/node_modules/generator-mn/node_modules/mem-fs-editor/lib/actions/copy.js:48:3)
    at module.exports.writing (/usr/local/lib/node_modules/generator-mn/generators/app/index.js:212:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-mn/node_modules/yeoman-generator/lib/index.js:399:25)
    at /usr/local/lib/node_modules/generator-mn/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/generator-mn/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/usr/local/lib/node_modules/generator-mn/node_modules/yeoman-generator/lib/index.js:400:11)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
`

**Comment by blikblum** [comment]
It's fixed in 0.5.3. Tested with elementary OS
